// <auto-generated />
using System;
using Demo02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo02.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo02.Models.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassRoomId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            ClassRoomId = 1,
                            ClassCode = "NET201",
                            ClassName = "Lập trình Web Nâng cao - Sáng"
                        },
                        new
                        {
                            ClassRoomId = 2,
                            ClassCode = "NET202",
                            ClassName = "Lập trình Web Nâng cao - Chiều"
                        });
                });

            modelBuilder.Entity("Demo02.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "annv@fpt.edu.vn",
                            FullName = "Nguyễn Văn An",
                            GPA = 8.5m,
                            PhoneNumber = "0901234567",
                            StudentCode = "PH12345"
                        },
                        new
                        {
                            StudentId = 2,
                            ClassRoomId = 1,
                            DateOfBirth = new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binhtt@fpt.edu.vn",
                            FullName = "Trần Thị Bình",
                            GPA = 9.2m,
                            PhoneNumber = "0907654321",
                            StudentCode = "PH12346"
                        },
                        new
                        {
                            StudentId = 3,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2003, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cuonglv@fpt.edu.vn",
                            FullName = "Lê Văn Cường",
                            GPA = 7.8m,
                            PhoneNumber = "0912345678",
                            StudentCode = "PH12347"
                        },
                        new
                        {
                            StudentId = 4,
                            ClassRoomId = 2,
                            DateOfBirth = new DateTime(2003, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dungpt@fpt.edu.vn",
                            FullName = "Phạm Thị Dung",
                            GPA = 8.9m,
                            PhoneNumber = "0923456789",
                            StudentCode = "PH12348"
                        });
                });

            modelBuilder.Entity("Demo02.Models.Student", b =>
                {
                    b.HasOne("Demo02.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("Demo02.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
