// <auto-generated />
using Demo01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo01.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo01.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            FullName = "Nguyen Van A",
                            Major = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            FullName = "Tran Thi B",
                            Major = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            FullName = "Le Van C",
                            Major = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            FullName = "Pham Thi D",
                            Major = "Graphic Design"
                        },
                        new
                        {
                            Id = 5,
                            Age = 18,
                            FullName = "Hoang Van E",
                            Major = "Business"
                        },
                        new
                        {
                            Id = 6,
                            Age = 20,
                            FullName = "Do Thi F",
                            Major = "IT"
                        },
                        new
                        {
                            Id = 7,
                            Age = 23,
                            FullName = "Ngo Van G",
                            Major = "Marketing"
                        },
                        new
                        {
                            Id = 8,
                            Age = 19,
                            FullName = "Bui Thi H",
                            Major = "Graphic Design"
                        },
                        new
                        {
                            Id = 9,
                            Age = 21,
                            FullName = "Vu Van I",
                            Major = "Business"
                        },
                        new
                        {
                            Id = 10,
                            Age = 22,
                            FullName = "Dinh Thi J",
                            Major = "IT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
