// <auto-generated />
using Demo02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo02.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo02.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Nguyen Van A",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Name = "Tran Thi B",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Le Van C",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Pham Thi D",
                            Status = "New"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = false,
                            Name = "Hoang Van E",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Do Thi F",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Ngo Van G",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
