// <auto-generated />
using Demo02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo02.Migrations
{
    [DbContext(typeof(RelationshipContext))]
    [Migration("20260114032752_RelationDB")]
    partial class RelationDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo02.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CustomerName = "Cong ty Alpha",
                            PhoneNo = "0901234567"
                        },
                        new
                        {
                            CustomerID = 2,
                            CustomerName = "Nha hang Beta",
                            PhoneNo = "0987654321"
                        },
                        new
                        {
                            CustomerID = 3,
                            CustomerName = "Khach san Gamma",
                            PhoneNo = "0912345678"
                        });
                });

            modelBuilder.Entity("Demo02.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "IT Software"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "HR Admin"
                        });
                });

            modelBuilder.Entity("Demo02.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DepartmentID = 1,
                            EmployeeName = "Nguyen Van A"
                        },
                        new
                        {
                            EmployeeID = 2,
                            DepartmentID = 1,
                            EmployeeName = "Tran Thi B"
                        },
                        new
                        {
                            EmployeeID = 3,
                            DepartmentID = 1,
                            EmployeeName = "Le Van C"
                        },
                        new
                        {
                            EmployeeID = 4,
                            DepartmentID = 2,
                            EmployeeName = "Pham Thi D"
                        },
                        new
                        {
                            EmployeeID = 5,
                            DepartmentID = 2,
                            EmployeeName = "Hoang Van E"
                        });
                });

            modelBuilder.Entity("Demo02.Models.Employee", b =>
                {
                    b.HasOne("Demo02.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Demo02.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
