// <auto-generated />
using System;
using Demo03.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo03.Migrations
{
    [DbContext(typeof(Demo03Context))]
    [Migration("20260116015338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo03.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AirportId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            City = "Hồ Chí Minh",
                            Code = "SGN",
                            Country = "Việt Nam",
                            Name = "Sân bay Quốc tế Tân Sơn Nhất"
                        },
                        new
                        {
                            AirportId = 2,
                            City = "Hà Nội",
                            Code = "HAN",
                            Country = "Việt Nam",
                            Name = "Sân bay Quốc tế Nội Bài"
                        },
                        new
                        {
                            AirportId = 3,
                            City = "Đà Nẵng",
                            Code = "DAD",
                            Country = "Việt Nam",
                            Name = "Sân bay Quốc tế Đà Nẵng"
                        });
                });

            modelBuilder.Entity("Demo03.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            ArrivalAirportId = 2,
                            ArrivalTime = new DateTime(2024, 6, 15, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 1,
                            DepartureTime = new DateTime(2024, 6, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "VN101",
                            Status = "Scheduled",
                            TotalSeats = 180
                        },
                        new
                        {
                            FlightId = 2,
                            ArrivalAirportId = 1,
                            ArrivalTime = new DateTime(2024, 6, 15, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 2,
                            DepartureTime = new DateTime(2024, 6, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "VN102",
                            Status = "Scheduled",
                            TotalSeats = 180
                        },
                        new
                        {
                            FlightId = 3,
                            ArrivalAirportId = 3,
                            ArrivalTime = new DateTime(2024, 6, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 1,
                            DepartureTime = new DateTime(2024, 6, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "VN201",
                            Status = "Scheduled",
                            TotalSeats = 150
                        });
                });

            modelBuilder.Entity("Demo03.Models.Flight", b =>
                {
                    b.HasOne("Demo03.Models.Airport", "ArrivalAirport")
                        .WithMany("ArrivingFlights")
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Demo03.Models.Airport", "DepartureAirport")
                        .WithMany("DepartingFlights")
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("Demo03.Models.Airport", b =>
                {
                    b.Navigation("ArrivingFlights");

                    b.Navigation("DepartingFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
